# Generated by Django 5.0.1 on 2024-12-23 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Confirmed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('sector', models.CharField(max_length=50)),
                ('paxNo', models.CharField(max_length=8)),
                ('agency', models.CharField(max_length=50)),
                ('airline', models.CharField(max_length=15)),
                ('flightno', models.IntegerField()),
                ('remarks', models.CharField(max_length=50)),
                ('reference', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('sector', models.CharField(max_length=50)),
                ('paxNo', models.CharField(max_length=8)),
                ('agency', models.CharField(max_length=50)),
                ('airline', models.CharField(max_length=15)),
                ('flightno', models.IntegerField()),
                ('remarks', models.CharField(max_length=50)),
                ('reference', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.BigIntegerField()),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
