# Generated by Django 5.0.1 on 2025-01-03 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_confirmed_staff_enquiry_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='FOC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('sector', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=50)),
                ('flightno', models.IntegerField()),
                ('paxno', models.IntegerField()),
                ('reference', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='enquiry',
            name='flightno',
        ),
        migrations.AddField(
            model_name='enquiry',
            name='flighttime',
            field=models.TimeField(default=None),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='status',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='ttl',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='confirmed',
            name='sector',
            field=models.CharField(choices=[('KTM/MTN', 'KTM-MTN'), ('KTM/PKR', 'KTM-PKR'), ('PKR/KTM', 'PKR-KTM'), ('KTM/BWA', 'KTM-BWA'), ('BWA/KTM', 'BWA-KTM'), ('KTM/BIR', 'KTM-BIR'), ('BIR/KTM', 'BIR-KTM'), ('KTM/KEP', 'KTM-KEP'), ('KEP/KTM', 'KEP-KTM'), ('KTM/BHR', 'KTM-BHR'), ('BHR/KTM', 'BHR-KTM'), ('KTM/SKH', 'KTM-SKH'), ('SKH/KTM', 'SKH-KTM'), ('KTM/DHI', 'KTM-DHI'), ('DHI/KTM', 'DHI-KTM'), ('PKR/BWA', 'PKR-BWA'), ('BWA/PKR', 'BWA-PKR'), ('PKR/BIR', 'PKR-BIR'), ('BIR/PKR', 'BIR-PKR'), ('PKR/KEP', 'PKR-KEP'), ('KEP/PKR', 'KEP-PKR'), ('PKR/BHR', 'PKR-BHR'), ('BHR/PKR', 'BHR-PKR'), ('KTM/LUA', 'KTM-LUA'), ('LUA/KTM', 'LUA-KTM'), ('KTM/PPL', 'KTM-PPL'), ('PPL/KTM', 'PPL-KTM'), ('KTM/TMI', 'KTM-TMI'), ('TMI/KTM', 'TMI-KTM'), ('KTM/RHP', 'KTM-RHP'), ('RHP/KTM', 'RHP-KTM'), ('LUA/PPL', 'LUA-PPL'), ('PPL/LUA', 'PPL-LUA'), ('LUA/TMI', 'LUA-TMI'), ('TMI/LUA', 'TMI-LUA'), ('PPL/TMI', 'PPL-TMI'), ('TMI/PPL', 'TMI-PPL'), ('LUA/RHP', 'LUA-RHP'), ('RHP/LUA', 'RHP-LUA'), ('PPL/RHP', 'PPL-RHP'), ('RHP/PPL', 'RHP-PPL'), ('PKR/JOM', 'PKR-JOM'), ('JOM/PKR', 'JOM-PKR'), ('KEP/IMK', 'KEP-IMK'), ('IMK/KEP', 'IMK-KEP'), ('KEP/DOP', 'KEP-DOP'), ('DOP/KEP', 'DOP-KEP')], max_length=50),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='sector',
            field=models.CharField(max_length=10),
        ),
    ]
